
ADVANTAGES_LIST = (["Name", "M/P/Soc", "X/Sup", "Cost", "Page"],
                   ["360 Vision", "P", "X", "25", "34"],
                   ["3D Spatial Sense", "P", "-", "10", "34"],
                   ["Absolute Direction", "P", "-", "5", "34"],
                   ["Absolute Timing", "M", "-", "2", "35"],
                   ["Accessory", "P", "X", "1", "100"],
                   ["Acute Hearing", "P", "-", "2/level", "35"],
                   ["Acute Taste and Smell", "P", "-", "2/level", "35"],
                   ["Acute Touch", "P", "-", "2/level", "35"],
                   ["Acute Vision", "P", "-", "2/level", "35"],
                   ["Administrative Rank", "Soc", "-", "5/level", "30"],
                   ["Affliction", "P", "X", "10/level", "35"],
                   ["Alcohol Tolerance", "P", "-", "1", "100"],
                   ["Allies(consult book)", "Soc", "-", "Variable===5", "36"],
                   ["Altered Time Rate", "M", "X", "100/level---3", "38"],
                   ["Alternate Form", "P", "X", "Variable===15", "83"],
                   ["Alternate Identity", "Soc", "-", "5 or 15", "39"],
                   ["Ambidexterity", "P", "-", "5", "39"],
                   ["Amphibious", "P", "X", "10", "40"],
                   ["Animal Empathy", "M", "-", "5", "40"],
                   ["Animal Friend", "M", "-", "5/level", "90"],
                   ["Arm DX", "P", "X", "12 or 16/level", "40"],
                   ["Arm ST", "P", "X", "3, 5, or 8/level", "40"],
                   ["Artificer", "M", "-", "10/level", "90"],
                   ["Autotrance", "M", "-", "1", "101"],
                   ["Binding", "P", "X", "2/level", "40"],
                   ["Blessed", "M", "Sup", "10, 10, or 20", "40"],
                   ["Brachiator", "P", "X", "5", "41"],
                   ["Breath-Holding", "P", "X", "2/level", "41"],
                   ["Business Acumen", "M", "-", "10/level", "90"],
                   ["Catfall", "P", "X", "10", "41"],
                   ["Chameleon", "P", "X", "5/level", "41"],
                   ["Channeling", "M", "Sup", "10", "41"],
                   ["Charisma", "M", "-", "5/level", "41"],
                   ["Chronolocation", "M", "-", "5", "35"],
                   ["Claim to Hospitality", "Soc", "-", "1/level---10", "41"],
                   ["Clairsentience", "M", "Sup", "50", "42"],
                   ["Claws(consult book)", "P", "X", "Variable===3", "42"],
                   ["Clerical Investment", "Soc", "-", "5", "43"],
                   ["Clinging", "P", "X", "20", "43"],
                   ["Combat Reflexes", "M", "-", "15", "43"],
                   ["Common Sense", "M", "-", "10", "43"],
                   ["Compartmentalized Mind", "M", "X", "50/level", "43"],
                   ["Constriction Attack", "P", "X", "15", "43"],
                   ["Contact Group(consult book)", "Soc", "-", "Variable===5", "44"],
                   ["Contacts(consult book)", "Soc", "-", "Variable===1", "44"],
                   ["Courtesy Rank", "Soc", "-", "1/level", "29"],
                   ["Cultural Adaptability", "M", "-", "10", "46"],
                   ["Cultural Familiarity(consult book)", "Soc", "-", "1 or 2/level", "23"],
                   ["Cybernetics(consult book)", "P", "-", "Variable===0", "46"],
                   ["Damage Resistance", "P", "X", "5/level", "46"],
                   ["Danger Sense", "M", "-", "15", "47"],
                   ["Daredevil", "M", "-", "15", "47"],
                   ["Dark Vision", "P", "X", "25", "47"],
                   ["Deep Sleeper", "P", "-", "1", "101"],
                   ["Destiny(consult book)", "M", "Sup", "5, 10, or 15", "48"],
                   ["Detect", "M/P", "X", "5, 10, 20, or 30", "48"],
                   ["Digital Mind", "P", "X", "5", "48"],
                   ["Discriminatory Hearing", "P", "X", "15", "49"],
                   ["Discriminatory Smell", "P", "X", "15", "49"],
                   ["Discriminatory Taste", "P", "X", "10", "49"],
                   ["Doesn't Breathe", "P", "X", "20", "49"],
                   ["Doesn't Eat or Drink", "P", "X", "10", "50"],
                   ["Doesn't Sleep", "P", "X", "20", "50"],
                   ["Dominance", "M", "Sup", "20", "50"],
                   ["Double-Jointed", "P", "-", "15", "56"],
                   ["Duplication", "M/P", "X", "35/level", "50"],
                   ["Eidetic Memory", "M", "-", "5", "51"],
                   ["Elastic Skin", "P", "X", "20", "51"],
                   ["Empathy", "M", "-", "15", "51"],
                   ["Enhanced Block", "M", "-", "5/level", "51"],
                   ["Enhanced Dodge", "M", "-", "15/level", "51"],
                   ["Enhanced Parry", "M", "-", "10/level", "51"],
                   ["Enhanced Move", "P", "X", "20/level", "52"],
                   ["Enhanced Time Sense", "M", "X", "45", "52"],
                   ["Enhanced Tracking", "P", "X", "5/level", "53"],
                   ["Extended Lifespan", "P", "X", "2/level", "53"],
                   ["Extra Arms", "P", "X", "10/level", "53"],
                   ["Extra Attack", "P", "-", "25/level", "53"],
                   ["Extra Head", "P", "X", "15/level", "54"],
                   ["Extra Legs", "P", "X", "5, 10, or 15", "54"],
                   ["Extra Life", "M", "X", "25/level", "55"],
                   ["Extra Mouth", "P", "X", "5/level", "55"],
                   ["Fashion Sense", "M", "-", "5", "21"],
                   ["Favor(consult book)", "Soc", "-", "Variable===1", "55"],
                   ["Fearlessness", "M", "-", "2/level", "55"],
                   ["Filter Lungs", "P", "X", "5", "55"],
                   ["Fit", "P", "-", "5", "55"],
                   ["Flexibility", "P", "-", "5", "56"],
                   ["Flight", "P", "X", "40", "56"],
                   ["Fur", "P", "X", "1", "101"],
                   ["Gadgeteer", "M", "-", "25 or 50", "56"],
                   ["G-Experience", "M", "-", "1/level---10", "57"],
                   ["Gifted Artist", "M", "-", "5/level", "90"],
                   ["Gizmos", "M", "-", "5/level", "57"],
                   ["Green Thumb", "M", "-", "5/level", "90"],
                   ["Growth", "P", "X", "10/level", "58"],
                   ["Gunslinger", "M", "-", "25", "58"],
                   ["Hard to Kill", "P", "-", "2/level", "58"],
                   ["Hard to Subdue", "P", "-", "2/level", "59"],
                   ["Healer", "M", "-", "10/level", "90"],
                   ["Healing", "M", "X", "30", "59"],
                   ["Hermaphromorph", "P", "X", "5", "59"],
                   ["High Manual Dexterity", "P", "-", "5/level", "59"],
                   ["High Pain Threshold", "P", "-", "10", "59"],
                   ["High TL", "M", "-", "5/level", "23"],
                   ["Higher Purpose", "M", "Sup", "5", "59"],
                   ["Honest Face", "P", "-", "1", "101"],
                   ["Hyperspectral Vision", "P", "X", "25", "60"],
                   ["Illuminated", "M", "Sup", "15", "60"],
                   ["Improved G-Tolerance", "P", "-", "5 or 10", "60"],
                   ["Independent Income", "Soc", "-", "1/level", "26"],
                   ["Indomitable", "M", "-", "15", "60"],
                   ["Infravision", "P", "X", "0 or 10", "60"], 
                   ["Injury Tolerance", "P", "X", "5, 20, 40, or 100", "60"],
                   ["Innate Burning Attack", "P", "X", "5/level", "61"],
                   ["Innate Corrosion Attack", "P", "X", "10/level", "61"],
                   ["Innate Crushing Attack", "P", "X", "5/level", "61"],
                   ["Innate Cutting Attack", "P", "X", "7/level", "61"],
                   ["Innate Fatigue Attack", "P", "X", "10/level", "61"],
                   ["Innate Impaling Attack", "P", "X", "8/level", "61"],
                   ["Innate Piercing Attack", "P", "X", "5/level", "61"],
                   ["Innate Toxic Attack", "P", "X", "4/level", "61"],
                   ["Insubstantiality", "M/P", "X", "80", "62"],
                   ["Intuition", "M", "-", "15", "63"],
                   ["Intuitive Mathematician", "M", "-", "5", "66"],
                   ["Invisibility", "M/P", "X", "40", "63"],
                   ["Jumper", "M", "Sup", "100", "64"],
                   ["Language Talent", "M", "-", "10", "65"],
                   ["Legal Enforcement Powers", "Soc", "-", "5, 10, or 15", "65"],
                   ["Legal Immunity", "Soc", "-", "5, 10, 10, 15, or 20", "65"],
                   ["Less Sleep", "P", "-", "2/level", "65"],
                   ["Lifting ST", "P", "X", "3/level", "65"],
                   ["Lightning Calculator", "M", "-", "2", "66"],
                   ["Longevity", "P", "-", "2", "66"],
                   ["Luck", "M", "-", "15, 30 or 60", "66"],
                   ["Magery", "M", "Sup", "5/level", "66"],
                   ["Magic Resistance", "M", "Sup", "2/level", "67"],
                   ["Mana Damper", "M", "Sup", "10/level", "67"],
                   ["Mana Enhancer", "M", "Sup", "50/level", "68"],
                   ["Mathematical Ability", "M", "-", "10/level", "90"],
                   ["Medium", "M", "Sup", "10", "68"],
                   ["Merchant Rank", "Soc", "-", "5 or 10/level", "30"],
                   ["Metabolism Control", "P", "X", "5/level", "68"],
                   ["Microscopic Vision", "P", "X", "5/level", "68"],
                   ["Military Rank", "Soc", "-", "5 or 10/level", "30"],
                   ["Mimicry", "M", "X", "10", "68"],
                   ["Mind Control", "M", "X", "50", "68"],
                   ["Mind Probe", "M", "X", "20", "69"],
                   ["Mind Reading", "M", "X", "30", "69"],
                   ["Mind Shield", "M", "X", "4/level", "70"],
                   ["Mindlink(consult book)", "M", "Sup", "Variable===5", "70"],
                   ["Modular Abilities(consult book)", "M/P", "X", "Variable===10", "71"],
                   ["Morph", "P", "X", "Variable===100", "84"],
                   ["Musical Ability", "M", "-", "5/level", "91"],
                   ["Neutralize", "M", "X", "50", "71"],
                   ["Nictitating Membrane", "P", "X", "1/level", "71"],
                   ["Night Vision", "P", "-", "1/level", "71"],
                   ["No Hangover", "P", "-", "1", "101"],
                   ["Obscure", "P", "X", "2/level", "72"],
                   ["Oracle", "M", "Sup", "15", "72"],
                   ["Outdoorsman", "M", "-", "10/level", "91"],
                   ["Parabolic Hearing", "P", "X", "4/level", "72"],
                   ["Patrons(consult book)", "Soc", "-", "Variable===10", "72"],
                   ["Payload", "P", "X", "1/level", "74"],
                   ["Penetrating Vision", "P", "X", "10/level", "74"],
                   ["Penetrating Voice", "P", "-", "1", "101"],
                   ["Perfect Balance", "P", "-", "15", "74"],
                   ["Peripheral Vision", "P", "-", "15", "74"],
                   ["Permeation", "P", "X", "5, 10, 20 or 40", "75"],
                   ["Photographic Memory", "M", "-", "10", "51"],
                   ["Pitiable", "Soc", "-", "5", "22"],
                   ["Plant Empathy", "M", "-", "5", "75"],
                   ["Police Rank", "Soc", "-", "5 or 10/level", "30"],
                   ["Possession", "M", "X", "100", "75"],
                   ["Power Investiture", "M", "Sup", "10/level", "77"],
                   ["Precognition", "M", "Sup", "25", "77"],
                   ["Pressure Support", "P", "X", "5, 10, or 15", "77"],
                   ["Protected Sense", "P", "X", "5/level", "78"],
                   ["Psi Static", "M", "Sup", "30", "78"],
                   ["Psychometry", "M", "Sup", "20", "78"],
                   ["Puppet", "M", "X", "5 or 10", "78"],
                   ["Racial Memory", "M", "X", "15 or 40", "78"],
                   ["Radiation Tolerance", "P", "X", "5/level---10", "79"],
                   ["Rank", "Soc", "-", "5 or 10/level", "29"],
                   ["Rapid Healing", "P", "-", "5", "79"],
                   ["Rapier Wit", "M", "-", "5", "79"],
                   ["Reawakened", "M", "Sup", "10", "80"],
                   ["Recovery", "P", "X", "10", "80"],
                   ["Reduced Consumption", "P", "-", "2/level", "80"],
                   ["Regeneration", "P", "X", "10, 25, 50, 100, or 150", "80"],
                   ["Regrowth", "P", "X", "40", "80"],
                   ["Religious Rank", "Soc", "-", "5 or 10/level", "30"],
                   ["Resistant", "P", "-", "5, 10, 15, 30", "80"],
                   ["Sanitized Metabolism", "P", "X", "1", "101"],
                   ["Scanning Sense", "P", "X", "20", "81"],
                   ["Sealed", "P", "X", "15", "82"],
                   ["Security Clearance", "Soc", "-", "5/level---3", "82"],
                   ["See Invisible", "P", "X", "15", "83"],
                   ["Sensitive", "M", "-", "5", "51"],
                   ["Sensitive Touch", "P", "X", "10", "83"],
                   ["Serendipity", "M", "-", "15/level", "83"],
                   ["Shadow Form", "P", "X", "50", "83"],
                   ["Shrinking", "P", "X", "5/level", "85"],
                   ["Shtick", "M/P", "-", "1", "101"],
                   ["Signature Gear", "Soc", "-", "1/level", "85"],
                   ["Silence", "P", "X", "5/level", "85"],
                   ["Single-Minded", "M", "-", "5", "85"],
                   ["Slippery", "P", "X", "2/level", "85"],
                   ["Smooth Operator", "M", "-", "15/level", "91"],
                   ["Snatcher", "M", "Sup", "80", "86"],
                   ["Social Chameleon", "M", "-", "5", "86"],
                   ["Social Regard", "Soc", "-", "5/level", "86"],
                   ["Speak Underwater", "P", "X", "5", "87"],
                   ["Speak With Animals", "M", "X", "25", "87"],
                   ["Speak With Plants", "M", "X", "15", "87"],
                   ["Special Rapport", "M", "Sup", "5", "88"],
                   ["Spines", "P", "X", "1 or 3", "88"],
                   ["Spirit Empathy", "M", "Sup", "10", "88"],
                   ["Status", "Soc", "-", "5/level", "28"],
                   ["Stretching", "P", "X", "6/level", "88"],
                   ["Striker", "P", "X", "5, 6, 7, or 8", "88"],
                   ["Striking ST", "P", "X", "5/level", "88"],
                   ["Subsonic Hearing", "P", "X", "0 or 5", "89"],
                   ["Subsonic Speech", "P", "X", "0 or 10", "89"],
                   ["Super Climbing", "P", "X", "3/level", "89"],
                   ["Super Jump", "P", "X", "10/level", "89"],
                   ["Super Luck", "M", "Sup", "100", "89"],
                   ["Supernatural Durability", "P", "Sup", "150", "89"],
                   ["Teeth", "P", "X", "0, 1, or 2", "91"],
                   ["Telecommunication", "M/P", "X", "10, 15, or 30", "91"],
                   ["Telekinesis", "M/P", "X", "5/level", "92"],
                   ["Telescopic Vision", "P", "X", "5/level", "92"],
                   ["Temperature Control", "M/P", "X", "5/level", "92"],
                   ["Temperature Tolerance", "P", "-", "1/level", "93"],
                   ["Temporal Inertia", "M", "Sup", "15", "93"],
                   ["Tenure", "Soc", "-", "5", "93"],
                   ["Terrain Adaptation", "P", "X", "0 or 5", "93"],
                   ["Terror", "M", "Sup", "30 + 10/level", "93"],
                   ["Trained By A Master", "M", "-", "30", "93"],
                   ["True Faith", "M", "Sup", "15", "94"],
                   ["Tunneling", "P", "X", "30 + 5/level", "94"],
                   ["Ultrahearing", "P", "X", "0 or 5", "94"],
                   ["Ultrasonic Speech", "P", "X", "0 or 10", "94"],
                   ["Ultravision", "P", "X", "0 or 10", "94"],
                   ["Unaging", "P", "X", "15", "95"],
                   ["Unfazeable", "M", "-", "15", "95"],
                   ["Universal Digestion", "P", "X", "5", "95"],
                   ["Unkillable", "P", "X", "50, 100, or 150", "95"],
                   ["Unusual Background", "M", "-", "0", "96"],
                   ["Vacuum Support", "P", "X", "5", "96"],
                   ["Vampiric Bite", "P", "X", "30 + 5/level", "96"],
                   ["Versatile", "M", "-", "5", "96"],
                   ["Very Fit", "P", "-", "15", "55"],
                   ["Very Rapid Healing", "P", "-", "15", "79"],
                   ["Vibration Sense", "P", "X", "10", "96"],
                   ["Visualization", "M", "Sup", "10", "96"],
                   ["Voice", "P", "-", "10", "97"],
                   ["Walk on Air", "P", "X", "20", "97"],
                   ["Walk on Liquid", "P", "X", "15", "97"],
                   ["Warp", "M", "Sup", "100", "97"],
                   ["Weapon Master", "M", "-", "20, 25, 30, 35, or 40", "99"],
                   ["Wild Talent", "M", "Sup", "20/level", "99"],
                   ["Xeno-Adaptability", "M", "-", "20", "46"],
                   ["Zeroed", "Soc", "-", "10", "100"],)

