

DISADVANTAGES_LIST = ( ["Name", "M/P/Soc", "X/Sup", "Cost", "Page"],
                       ["Absent-Mindedness", "M", "–", "-15", "122"],
                       ["Acceleration Weakness", "P", "–", "-1", "165"],
                       ["Addiction", "M/P", "–", "Variable 122, 164,", "165"],
                       ["Alcohol Intolerance", "P", "–", "-1", "165"],
                       ["Alcoholism", "P", "–", "-15 or -20", "122"],
                       ["Amnesia", "M", "–", "-10 or -25", "123"],
                       ["Appearance", "P", "–", "Variable", "21"],
                       ["Attentive", "M", "–", "-1", "163"],
                       ["Bad Back", "P", "–", "-15 or -25", "123"],
                       ["Bad Grip", "P", "–", "-5/level", "123"],
                       ["Bad Sight", "P", "–", "-25", "123"],
                       ["Bad Smell", "P", "–", "-10", "124"],
                       ["Bad Temper", "M", "–", "-10*", "124"],
                       ["Berserk", "M", "–", "-10*", "124"],
                       ["Bestial", "M", "X", "-10 or -15", "124"],
                       ["Blindness", "P", "–", "-50", "124"],
                       ["Bloodlust", "M", "–", "-10*", "125"],
                       ["Bowlegged", "P", "–", "-1", "165"],
                       ["Broad-Minded", "M", "–", "-1", "163"],
                       ["Bully", "M", "–", "-10*", "125"],
                       ["Callous", "M", "–", "-5", "125"],
                       ["Cannot Float", "P", "–", "-1", "165"],
                       ["Cannot Learn", "M", "–", "-30", "125"],
                       ["Cannot Speak", "P", "–", "-15", "125"],
                       ["Careful", "M", "–", "-1", "163"],
                       ["Charitable", "M", "–", "-15*", "125"],
                       ["Chauvinistic", "M", "–", "-1", "163"],
                       ["Chronic Depression", "M", "–", "-15*", "126"],
                       ["Chronic Pain", "P", "–", "Variable", "126"],
                       ["Chummy", "M", "–", "-5", "126"],
                       ["Clueless", "M", "–", "-10", "126"],
                       ["Code of Honor", "M", "–", "-1 or -5 to -15 127,", "163"],
                       ["Cold-Blooded", "P", "X", "-5 or -10", "127"],
                       ["Colorblindness", "P", "–", "-10", "127"],
                       ["Combat Paralysis", "P", "–", "-15", "127"],
                       ["Compulsive Behavior", "M", "–", "-5 to -15*", "128"],
                       ["Confused", "M", "–", "-10*", "129"],
                       ["Congenial", "M", "–", "-1", "164"],
                       ["Cowardice", "M", "–", "-10*", "129"],
                       ["Curious", "M", "–", "-5*", "129"],
                       ["Cursed", "M", "Sup", "-75", "129"],
                       ["Deafness", "P", "–", "-20", "129"],
                       ["Debt", "Soc", "–", "-1/level", "26"],
                       ["Decreased Time Rate", "M", "X", "-100", "129"],
                       ["Delusions", "M", "–", "-1 or -5 to -15 130,", "164"],
                       ["Dependency", "P", "X", "Variable", "130"],
                       ["Dependents", "Soc", "–", "Variable", "131"],
                       ["Destiny", "M", "Sup", "Variable", "131"],
                       ["Disciplines of Faith", "M", "–", "-5 to -15", "132"],
                       ["Dislikes", "M", "–", "-1", "164"],
                       ["Distinctive Features", "P", "–", "-1", "165"],
                       ["Distractible", "M", "–", "-1", "164"],
                       ["Disturbing Voice", "P", "–", "-10", "132"],
                       ["Divine Curse", "M", "Sup", "Variable", "132"],
                       ["Draining", "P", "Sup", "Variable", "132"],
                       ["Dread", "M", "Sup", "Variable", "132"],
                       ["Dreamer", "M", "–", "-1", "164"],
                       ["Dull", "M", "–", "-1", "164"],
                       ["Duty", "Soc", "–", "Variable", "133"],
                       ["Dwarfism", "P", "–", "-15", "19"],
                       ["Dyslexia", "M", "–", "-10", "134"],
                       ["Easy to Kill", "P", "–", "-2/level", "134"],
                       ["Easy to Read", "M", "–", "-10", "134"],
                       ["Electrical", "P", "X", "-20", "134"],
                       ["Enemies", "Soc", "–", "Variable", "135"],
                       ["Epilepsy", "P", "–", "-30", "136"],
                       ["Extra Sleep", "P", "–", "-2/level", "136"],
                       ["Fanaticism", "M", "–", "-15", "136"],
                       ["Fat", "P", "–", "-3", "19"],
                       ["Fearfulness", "M", "–", "-2/level", "136"],
                       ["Flashbacks", "M", "–", "Variable", "136"],
                       ["Fragile", "P", "X", "Variable", "136"],
                       ["Frightens Animals", "M", "Sup", "-10", "137"],
                       ["G-Intolerance", "P", "–", "-10 or -20", "137"],
                       ["Gigantism", "P", "–", "0", "20"],
                       ["Gluttony", "M", "–", "-5*", "137"],
                       ["Greed", "M", "–", "-15*", "137"],
                       ["Gregarious", "M", "–", "-10", "126"],
                       ["Guilt Complex", "M", "–", "-5", "137"],
                       ["Gullibility", "M", "–", "-10*", "137"],
                       ["Habits or Expressions", "M", "–", "-1", "164"],
                       ["Ham-Fisted", "P", "–", "-5 or -10", "138"],
                       ["Hard of Hearing", "P", "–", "-10", "138"],
                       ["Hemophilia", "P", "–", "-30", "138"],
                       ["Hidebound", "M", "–", "-5", "138"],
                       ["Honesty", "M", "–", "-10*", "138"],
                       ["Horizontal", "P", "X", "-10", "139"],
                       ["Horrible Hangovers", "P", "–", "-1", "165"],
                       ["Humble", "M", "–", "-1", "164"],
                       ["Hunchback", "P", "–", "-10", "139"],
                       ["Imaginative", "M", "–", "-1", "164"],
                       ["Impulsiveness", "M", "–", "-10*", "139"],
                       ["Incompetence", "M", "–", "-1", "164"],
                       ["Increased Consumption", "P", "–", "-10/level", "139"],
                       ["Increased Life Support", "P", "X", "Variable", "139"],
                       ["Incurious", "M", "–", "-5*", "140"],
                       ["Indecisive", "M", "–", "-10*", "140"],
                       ["Infectious Attack", "P", "Sup", "-5", "140"],
                       ["Innumerate", "M", "–", "-5", "140"],
                       ["Insomniac", "P", "–", "-10 or -15", "140"],
                       ["Intolerance", "M", "–", "Variable", "140"],
                       ["Invertebrate", "P", "X", "-20", "140"],
                       ["Jealousy", "M", "–", "-10", "140"],
                       ["Killjoy", "P", "–", "-15", "140"],
                       ["Kleptomania", "M", "–", "-15*", "141"],
                       ["Klutz", "P", "–", "-5", "141"],
                       ["Lame", "P", "–", "-10 to -30", "141"],
                       ["Laziness", "M", "–", "-10", "142"],
                       ["Lecherousness", "M", "–", "-15*", "142"],
                       ["Lifebane", "M", "Sup", "-10", "142"],
                       ["Light Sleeper", "P", "–", "-5", "142"],
                       ["Likes", "M", "–", "-1", "164"],
                       ["Loner", "M", "–", "-5*", "142"],
                       ["Low Empathy", "M", "–", "-20", "142"],
                       ["Low Pain Threshold", "P", "–", "-10", "142"],
                       ["Low Self-Image", "M", "–", "-10", "143"],
                       ["Low TL", "M", "–", "-5/level", "22"],
                       ["Lunacy", "M", "–", "-10", "143"],
                       ["Magic Susceptibility", "M", "Sup", "-3/level", "143"],
                       ["Maintenance", "P", "–", "Variable", "143"],
                       ["Manic-Depressive", "M", "–", "-20", "143"],
                       ["Megalomania", "M", "–", "-10", "144"],
                       ["Minor Handicaps", "P", "–", "-1", "165"],
                       ["Miserliness", "M", "–", "-10*", "144"],
                       ["Missing Digit", "P", "–", "-2 or -5", "144"],
                       ["Mistaken Identity", "P", "–", "-5", "21"],
                       ["Motion Sickness", "P", "–", "-10", "144"],
                       ["Mundane Background", "M", "–", "-10", "144"],
                       ["Mute", "P", "–", "-25", "125"],
                       ["Nervous Stomach", "P", "–", "-1", "165"],
                       ["Neurological Disorder", "P", "–", "Variable", "144"],
                       ["Neutered", "P", "–", "-1", "165"],
                       ["Night Blindness", "P", "–", "-10", "144"],
                       ["Nightmares", "M", "–", "-5*", "144"],
                       ["No Depth Perception", "P", "–", "-15", "145"],
                       ["No Fine Manipulators", "P", "X", "-30", "145"],
                       ["No Legs", "P", "X", "Variable", "145"],
                       ["No Manipulators", "P", "X", "-50", "145"],
                       ["No Sense of Humor", "M", "–", "-10", "146"],
                       ["No Sense of Smell/Taste", "P", "–", "-5", "146"],
                       ["Nocturnal", "P", "X", "-20", "146"],
                       ["Noisy", "P", "–", "-2/level", "146"],
                       ["Non-Iconographic", "M", "–", "-10", "146"],
                       ["Nosy", "M", "–", "-1", "164"],
                       ["Numb", "P", "–", "-20", "146"],
                       ["Oblivious", "M", "–", "-5", "146"],
                       ["Obsession", "M", "–", "-1, -5, or -10* 146,", "164"],
                       ["Odious Personal Habits", "M", "–", "-5, -10, or -15", "22"],
                       ["On the Edge", "M", "–", "-15*", "146"],
                       ["One Arm", "P", "–", "-20", "147"],
                       ["One Eye", "P", "–", "-15", "147"],
                       ["One Hand", "P", "–", "-15", "147"],
                       ["Overconfidence", "M", "–", "-5*", "148"],
                       ["Overweight", "P", "–", "-1", "19"],
                       ["Pacifism", "M", "–", "Variable", "148"],
                       ["Paranoia", "M", "–", "-10", "148"],
                       ["Personality Change", "M", "–", "-1", "164"],
                       ["Phantom Voices", "M", "–", "-5 to -15", "148"],
                       ["Phobias", "M", "–", "Variable*", "148"],
                       ["Post-Combat Shakes", "M", "–", "-5*", "150"],
                       ["Proud", "M", "–", "-1", "164"],
                       ["Pyromania", "M", "–", "-5*", "150"],
                       ["Quadriplegic", "P", "–", "-80", "150"],
                       ["Reprogrammable", "M", "X", "-10", "150"],
                       ["Reputation", "Soc", "–", "Variable", "26"],
                       ["Responsive", "M", "–", "-1", "164"],
                       ["Restricted Diet", "P", "–", "-10 to -40", "151"],
                       ["Restricted Vision", "P", "–", "-15 or -30", "151"],
                       ["Revulsion", "P", "Sup", "-5 to -15", "151"],
                       ["Sadism", "M", "–", "-15*", "152"],
                       ["Secret", "Soc", "–", "-5 to -30", "152"],
                       ["Secret Identity", "Soc", "–", "Variable", "153"],
                       ["Self-Destruct", "P", "X", "-10", "153"],
                       ["Selfish", "M", "–", "-5*", "153"],
                       ["Selfless", "M", "–", "-5*", "153"],
                       ["Semi-Upright", "P", "X", "-5", "153"],
                       ["Sense of Duty", "M", "–", "-2 to -20", "153"],
                       ["Sexless", "P", "X", "-1", "165"],
                       ["Shadow Form", "P", "X", "-20", "153"],
                       ["Short Attention Span", "M", "–", "-10*", "153"],
                       ["Short Lifespan", "P", "X", "-10/level", "154"],
                       ["Shyness", "M", "–", "-5, -10, or -20", "154"],
                       ["Skinny", "P", "–", "-5", "18"],
                       ["Slave Mentality", "M", "–", "-40", "154"],
                       ["Sleepwalker", "M", "–", "-5*", "154"],
                       ["Sleepy", "P", "X", "Variable", "154"],
                       ["Slow Eater", "P", "X", "-10", "155"],
                       ["Slow Healing", "P", "–", "-5/level", "155"],
                       ["Slow Riser", "P", "–", "-5", "155"],
                       ["Social Disease", "P", "–", "-5", "155"],
                       ["Social Stigma", "Soc", "–", "-5 to -20", "155"],
                       ["Space Sickness", "P", "–", "-10", "156"],
                       ["Split Personality", "M", "–", "-15*", "156"],
                       ["Squeamish", "M", "–", "-10*", "156"],
                       ["Staid", "M", "–", "-1", "164"],
                       ["Status", "Soc", "–", "-5/level", "28"],
                       ["Stress Atavism", "M", "X", "Variable*", "156"],
                       ["Stubbornness", "M", "–", "-5", "157"],
                       ["Stuttering", "P", "–", "-10", "157"],
                       ["Supernatural Features", "P", "Sup", "Variable", "157"],
                       ["Supersensitive", "M", "Sup", "-15", "158"],
                       ["Susceptible", "P", "–", "Variable", "158"],
                       ["Terminally Ill", "P", "–", "-50, -75, or -100", "158"],
                       ["Timesickness", "P", "–", "-10", "158"],
                       ["Total Klutz", "P", "–", "-15", "141"],
                       ["Trademark", "M", "–", "-1 or -5 to -15 159,", "164"],
                       ["Trickster", "M", "–", "-15*", "159"],
                       ["Truthfulness", "M", "–", "-5*", "159"],
                       ["Uncongenial", "M", "–", "-1", "165"],
                       ["Uncontrollable Appetite", "M", "Sup", "-15*", "159"],
                       ["Unfit", "P", "–", "-5", "160"],
                       ["Unhealing", "P", "X", "-20 or -30", "160"],
                       ["Unique", "M", "Sup", "-5", "160"],
                       ["Unluckiness", "M", "–", "-10", "160"],
                       ["Unnatural Features", "P", "–", "Variable", "22"],
                       ["Unusual Biochemistry", "P", "X", "-5", "160"],
                       ["Very Fat", "P", "–", "-5", "19"],
                       ["Very Unfit", "P", "–", "-15", "160"],
                       ["Vow", "M", "–", "-1 or -5 to -15 160,", "165"],
                       ["Vulnerability", "P", "X", "Variable", "161"],
                       ["Weak Bite", "P", "X", "-2", "161"],
                       ["Weakness", "P", "X", "Variable", "161"],
                       ["Wealth", "Soc", "–", "Variable", "25"],
                       ["Weirdness Magnet", "M", "Sup", "-15", "161"],
                       ["Workaholic", "M", "–", "-5", "162"],
                       ["Wounded", "P", "–", "-5", "162"],
                       ["Xenophilia", "M", "–", "-10*", "163"],
                       )